version: '3.9'

services:
  cleanarchitecturebackend:
    image: cleanarchitecturebackend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      HOST: ${HOST}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
